In [1]:
# Importer les packages
import pandas as pd
from requests import get # récupérer le contenu html de la page
from bs4 import BeautifulSoup as bs # s'assurer d'avoir le contenu dans un objet bs bien sparsifié
# install sqlite3
!pip install db-sqlite3

Collecting db-sqlite3
  Downloading db-sqlite3-0.0.1.tar.gz (1.4 kB)
  Preparing metadata (setup.py) ... done
Collecting db (from db-sqlite3)
  Downloading db-0.1.1.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Collecting antiorm (from db->db-sqlite3)
  Downloading antiorm-1.2.1.tar.gz (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: db-sqlite3, db, antiorm
  Building wheel for db-sqlite3 (setup.py) ... done
  Created wheel for db-sqlite3: filename=db_sqlite3-0.0.1-py3-none-any.whl size=1768 sha256=6a16ac1e429a63230ce90c77f47c1010252fa932f94ab9ff73bbf4e607dc4709
  Stored in directory: /root/.cache/pip/wheels/fe/5a/c7/5bc48efba8859978617693442869e925d6f51447c0c9521a53
  Building wheel for db (setup.py) ... done
  Created wheel for db: filename=db-0.1.1-py3-none-any.whl size=3873 sha256=020f234c9ad9a044cb9d15efa720ed483711968b95c11f0e2f3ff1e94e992890
  Stored in directory: /root/.cache/pip/wheels/b3/be/81/a4ce37a0114cd102481c28ff6951d63be24e0c3750af04e4e7
  Building wheel for antiorm (setup.py) ... done
  Created wheel for antiorm: filename=antiorm-1.2.1-py3-none-any.whl size=31666 sha256=f20314021476098609d16ffec85a9952c51d2bde1069c3ab7a6f4d806599cec8
  Stored in directory: /root/.cache/pip/wheels/59/f2/19/6d79c922072d86a15f1e89bea01335e989cf0a60038d6b3b1e
Successfully built db-sqlite3 db antiorm
Installing collected packages: antiorm, db, db-sqlite3
Successfully installed antiorm-1.2.1 db-0.1.1 db-sqlite3-0.0.1


**CHIEN**

In [2]:
# url
url = 'https://sn.coinafrique.com/categorie/chiens?page=1'
# récupérer le contenu de la page
res= get(url)
# res.content # pour voir le contenu de la page
# Avoir le contenu dans un objet bs et bien sparsifier
soup = bs(res.content, 'html.parser')

In [3]:
# récupérer les conteneurs
containers = soup.find_all('div', 'col s6 m4 l3')
len(containers)

84

In [4]:
# premier container
container = containers[0]
# container
# Name chien
name_c = container.find('p', 'ad__card-description').a.text
# name_c
# price
price_c = container.find('p', 'ad__card-price').text.strip('CFA')
#price_c
# adress chien
adress_c = container.find('p', 'ad__card-location').span.text
#adress_c
# url image chien
url_image_c = container.find('img', 'ad__card-img')['src']
print(name_c,'--',price_c, '--',adress_c, '--', url_image_c)

Chiots -- 150 000 -- Diamniadio, Sénégal -- https://images.coinafrique.com/thumb_5782568_uploaded_image1_1771523397.jpg

In [5]:
# récupérer les informations sur tous les containers
data = []
for container in containers:
  try:
    # Name chien
    name_c = container.find('p', 'ad__card-description').a.text
    # price chien
    price_c = container.find('p', 'ad__card-price').text.strip('CFA')
    # adress chien
    adress_c = container.find('p', 'ad__card-location').span.text
    # url image chien
    url_image_c = container.find('img', 'ad__card-img')['src']
    dic = {
        'name_c': name_c,
        'price_c': price_c,
        'adress_c': adress_c,
        'url_image_c':url_image_c
    }
    data.append(dic)
  except:
    pass

# Dataframe
DF1 = pd.DataFrame(data)

In [6]:
DF1.head()

,name_c,price_c,adress_c,url_image_c
0,Chiots,150 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5782568_u...
1,Berger Belge Malinois,250 000,"Sicap Liberté, Dakar, Sénégal",https://images.coinafrique.com/thumb_5777856_u...
2,Chien,100 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5769939_u...
3,Chiot Bouledogues français,Prix sur demande,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5757166_u...
4,Chiots Berger Allemand,150 000,"Guediawaye, Dakar, Sénégal",https://images.coinafrique.com/thumb_5751732_u...

In [7]:
DF1.shape

(84, 4)

In [8]:
# scraper les données sur plusieurs
df1_final = pd.DataFrame()
for ind_page in range(1, 12):
  # url
  url = 'https://sn.coinafrique.com/categorie/chiens?page={ind_page}'
  # récupérer le contenu de la page
  res= get(url)
  # res.content # pour voir le contenu de la page
  # Avoir le contenu dans un objet bs et bien sparsifier
  soup = bs(res.content, 'html.parser')
  # récupérer les conteneurs
  containers = soup.find_all('div', 'col s6 m4 l3')
  len(containers)

  data = []
  for container in containers:
    try:
      # Name chien
      name_c = container.find('p', 'ad__card-description').a.text
      # price chien
      price_c = container.find('p', 'ad__card-price').text.strip('CFA')
      # adress chien
      adress_c = container.find('p', 'ad__card-location').span.text
      # url image chien
      url_image_c = container.find('img', 'ad__card-img')['src']
      dic = {
          'name_c': name_c,
          'price_c': price_c,
          'adress_c': adress_c,
          'url_image_c':url_image_c
      }
      data.append(dic)
    except:
      pass

  # Dataframe
  DF1 = pd.DataFrame(data)
  df1_final = pd.concat([df1_final, DF1], axis = 0).reset_index(drop = True)

In [9]:
# Afficher df_final
df1_final.head()

,name_c,price_c,adress_c,url_image_c
0,Chiots,150 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5782568_u...
1,Berger Belge Malinois,250 000,"Sicap Liberté, Dakar, Sénégal",https://images.coinafrique.com/thumb_5777856_u...
2,Chien,100 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5769939_u...
3,Chiot Bouledogues français,Prix sur demande,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5757166_u...
4,Chiots Berger Allemand,150 000,"Guediawaye, Dakar, Sénégal",https://images.coinafrique.com/thumb_5751732_u...

In [10]:
# Dimension
df1_final.shape

(504, 4)

**MOUTON**

In [11]:
# url
url = 'https://sn.coinafrique.com/categorie/moutons?page=1'
# récupérer le contenu de la page
res= get(url)
# res.content # pour voir le contenu de la page
# Avoir le contenu dans un objet bs et bien sparsifier
soup = bs(res.content, 'html.parser')

In [12]:
# récupérer les conteneurs
containers = soup.find_all('div', 'col s6 m4 l3')
len(containers)

84

In [13]:
# premier container
container = containers[0]
# container
# Name mouton
name_m = container.find('p', 'ad__card-description').a.text
# price mouton
price_m = container.find('p', 'ad__card-price').text.strip('CFA')
# adress mouton
adress_m = container.find('p', 'ad__card-location').span.text
# url image mouton
url_image_m = container.find('img','ad__card-img')['src']
print(name_m,'--',price_m, '--',adress_m, '--', url_image_m)

Femelle Ladoum -- 400 -- Rufisque, Sénégal -- https://images.coinafrique.com/thumb_5796356_uploaded_image1_1772218342.jpg

In [14]:
# récupérer les informations sur tous les containers
data = []
for container in containers:
  try:
    # Name mouton
    name_m = container.find('p', 'ad__card-description').a.text
    # price mouton
    price_m = container.find('p', 'ad__card-price').text.strip('CFA')
    # adress mouton
    adress_m = container.find('p', 'ad__card-location').span.text
    # url image mouton
    url_image_m = container.find('img','ad__card-img')['src']
    dic = {
        'name_m': name_m,
        'price_m': price_m,
        'adress_m': adress_m,
        'url_image_m':url_image_m
    }
    data.append(dic)
  except:
    pass

# Dataframe
DF2 = pd.DataFrame(data)

In [15]:
DF2.head()

,name_m,price_m,adress_m,url_image_m
0,Femelle Ladoum,400,"Rufisque, Sénégal",https://images.coinafrique.com/thumb_5796356_u...
1,Mouton Ladoum,650 000,"Ndiass, Sénégal",https://images.coinafrique.com/thumb_5779027_u...
2,Mâle ladoum,650 000,"Keur Massar, Sénégal",https://images.coinafrique.com/thumb_5777868_u...
3,Femelle Ladoum,300 000,"Grand Dakar, Dakar, Sénégal",https://images.coinafrique.com/thumb_5731575_u...
4,Femelle métisse ladoum,150 000,"Mermoz-Sacré Coeur, Dakar, Sénégal",https://images.coinafrique.com/thumb_5716188_u...

In [16]:
# scraper les données sur plusieurs
df2_final = pd.DataFrame()
for ind_page in range(1, 17):
  # url
  url = 'https://sn.coinafrique.com/categorie/moutons?page={ind_page}'
  # récupérer le contenu de la page
  res= get(url)
  # res.content # pour voir le contenu de la page
  # Avoir le contenu dans un objet bs et bien sparsifier
  soup = bs(res.content, 'html.parser')
  containers = soup.find_all('div', 'col s6 m4 l3')
  # récupérer les informations sur tous les containers
  data = []
  for container in containers:
    try:
      # Name mouton
      name_m = container.find('p', 'ad__card-description').a.text
      # price mouton
      price_m = container.find('p', 'ad__card-price').text.strip('CFA')
      # adress mouton
      adress_m = container.find('p', 'ad__card-location').span.text
      # url image mouton
      url_image_m = container.find('img','ad__card-img')['src']
      dic = {
          'name_m': name_m,
          'price_m': price_m,
          'adress_m': adress_m,
          'url_image_m':url_image_m
      }
      data.append(dic)
    except:
      pass

# Dataframe
  DF2 = pd.DataFrame(data)
  df2_final = pd.concat([df2_final, DF2], axis = 0).reset_index(drop = True)

In [17]:
df2_final.head()

,name_m,price_m,adress_m,url_image_m
0,Femelle Ladoum,400,"Rufisque, Sénégal",https://images.coinafrique.com/thumb_5796356_u...
1,Mouton Ladoum,650 000,"Ndiass, Sénégal",https://images.coinafrique.com/thumb_5779027_u...
2,Mâle ladoum,650 000,"Keur Massar, Sénégal",https://images.coinafrique.com/thumb_5777868_u...
3,Femelle Ladoum,300 000,"Grand Dakar, Dakar, Sénégal",https://images.coinafrique.com/thumb_5731575_u...
4,Femelle métisse ladoum,150 000,"Mermoz-Sacré Coeur, Dakar, Sénégal",https://images.coinafrique.com/thumb_5716188_u...

In [18]:
# Dimension
df2_final.shape

(1008, 4)

**POULES, LAPINS & PIGEONS**

In [19]:
# url
url = 'https://sn.coinafrique.com/categorie/poules-lapins-et-pigeons?page=1'
# récupérer le contenu de la page
res= get(url)
# res.content # pour voir le contenu de la page
# Avoir le contenu dans un objet bs et bien sparsifier
soup = bs(res.content, 'html.parser')

In [20]:
# récupérer les conteneurs
containers = soup.find_all('div', 'col s6 m4 l3')
len(containers)

84

In [21]:
# premier container
container = containers[0]
# container
# details p,l,pig
details_p_l_pig = container.find('p', 'ad__card-description').a.text
# price p,l,pig
price_p_l_pig = container.find('p', 'ad__card-price').text.strip('CFA')
# adress p,l,pig
adress_p_l_pig = container.find('p', 'ad__card-location').span.text
# url image p,l,pig
url_image_p_l_pig = container.find('img','ad__card-img')['src']
print(details_p_l_pig,'--',price_p_l_pig, '--',adress_p_l_pig, '--', url_image_p_l_pig)

Cochin caillouté -- Prix sur demande -- Pikine, Sénégal -- https://images.coinafrique.com/thumb_5795056_uploaded_image1_1772163078.jpg

In [22]:
# récupérer les informations sur tous les containers
data = []
for container in containers:
  try:
    # details p,l,pig
    details_p_l_pig = container.find('p', 'ad__card-description').a.text
    # price p,l,pig
    price_p_l_pig = container.find('p', 'ad__card-price').text.strip('CFA')
    # adress p,l,pig
    adress_p_l_pig = container.find('p', 'ad__card-location').span.text
    # url image p,l,pig
    url_image_p_l_pig = container.find('img','ad__card-img')['src']
    dic = {
        'details_p_l_pig': details_p_l_pig,
        'price_p_l_pig': price_p_l_pig,
        'adress_p_l_pig': adress_p_l_pig,
        'url_image_p_l_pig': url_image_p_l_pig
    }
    data.append(dic)
  except:
    pass

# Dataframe
DF3 = pd.DataFrame(data)

In [23]:
DF3.head()

,details_p_l_pig,price_p_l_pig,adress_p_l_pig,url_image_p_l_pig
0,Cochin caillouté,Prix sur demande,"Pikine, Sénégal",https://images.coinafrique.com/thumb_5795056_u...
1,Poussin hermine,7 500,"Ouakam, Dakar, Sénégal",https://images.coinafrique.com/thumb_5786408_u...
2,Lapereaux,Prix sur demande,"Thies, Sénégal",https://images.coinafrique.com/thumb_5782021_u...
3,Poulets de chair,3 000,"Dakar, Sénégal",https://images.coinafrique.com/thumb_5780864_u...
4,Brahman herminé,35 000,"Dakar, Sénégal",https://images.coinafrique.com/thumb_5778994_u...

In [24]:
# scraper les données sur plusieurs
df3_final = pd.DataFrame()
for ind_page in range(1, 11):
  # url
  url = 'https://sn.coinafrique.com/categorie/poules-lapins-et-pigeons?page={ind_page}'
  # récupérer le contenu de la page
  res= get(url)
  # res.content # pour voir le contenu de la page
  # Avoir le contenu dans un objet bs et bien sparsifier
  soup = bs(res.content, 'html.parser')
  containers = soup.find_all('div', 'col s6 m4 l3')
  # récupérer les informations sur tous les containers
  data = []
  for container in containers:
    try:
      # details p,l,pig
      details_p_l_pig = container.find('p', 'ad__card-description').a.text
      # price p,l,pig
      price_p_l_pig = container.find('p', 'ad__card-price').text.strip('CFA')
      # adress p,l,pig
      adress_p_l_pig = container.find('p', 'ad__card-location').span.text
      # url image p,l,pig
      url_image_p_l_pig = container.find('img','ad__card-img')['src']
      dic = {
          'details_p_l_pig': details_p_l_pig,
          'price_p_l_pig': price_p_l_pig,
          'adress_p_l_pig': adress_p_l_pig,
          'url_image_p_l_pig': url_image_p_l_pig
      }
      data.append(dic)
    except:
      pass

  # Dataframe
  DF3 = pd.DataFrame(data)
  df3_final = pd.concat([df3_final, DF3], axis = 0).reset_index(drop = True)

In [25]:
# Afficher df_final
df3_final.head()

,details_p_l_pig,price_p_l_pig,adress_p_l_pig,url_image_p_l_pig
0,Cochin caillouté,Prix sur demande,"Pikine, Sénégal",https://images.coinafrique.com/thumb_5795056_u...
1,Poussin hermine,7 500,"Ouakam, Dakar, Sénégal",https://images.coinafrique.com/thumb_5786408_u...
2,Lapereaux,Prix sur demande,"Thies, Sénégal",https://images.coinafrique.com/thumb_5782021_u...
3,Poulets de chair,3 000,"Dakar, Sénégal",https://images.coinafrique.com/thumb_5780864_u...
4,Brahman herminé,35 000,"Dakar, Sénégal",https://images.coinafrique.com/thumb_5778994_u...

In [27]:
# Dimension
df3_final.shape

(840, 4)

**AUTRES ANIMAUX**

In [28]:
# url
url = 'https://sn.coinafrique.com/categorie/autres-animaux?page=1'
# récupérer le contenu de la page
res= get(url)
# Avoir le contenu dans un objet bs et bien sparsifier
soup = bs(res.content, 'html.parser')

In [29]:
# récupérer les conteneurs
containers = soup.find_all('div', 'col s6 m4 l3')
len(containers)

84

In [30]:
# premier container
container = containers[0]
# container
# Name aut anim
name_a_an = container.find('p', 'ad__card-description').a.text
# price aut anim
price_a_an = container.find('p', 'ad__card-price').text.strip('CFA')
# adress aut anim
adress_a_an = container.find('p', 'ad__card-location').span.text
# url image aut anim
url_image_a_an = container.find('img','ad__card-img')['src']
print(name_a_an,'--',price_a_an, '--',adress_a_an, '--', url_image_a_an)

Canard de barbarie -- 12 000 -- Diamniadio, Sénégal -- https://images.coinafrique.com/thumb_5769889_uploaded_image1_1770826381.jpg

In [31]:
# récupérer les informations sur tous les containers
data = []
for container in containers:
  try:
    # Name aut anim
    name_a_an = container.find('p', 'ad__card-description').a.text
    # price aut anim
    price_a_an = container.find('p', 'ad__card-price').text.strip('CFA')
    # adress aut anim
    adress_a_an = container.find('p', 'ad__card-location').span.text
    # url image aut anim
    url_image_a_an = container.find('img','ad__card-img')['src']
    dic = {
        'name_a_an': name_a_an,
        'price_a_an': price_a_an,
        'adress_a_an': adress_a_an,
        'url_image_a_an':url_image_a_an
    }
    data.append(dic)
  except:
    pass

# Dataframe
DF4 = pd.DataFrame(data)

In [32]:
DF4.head()

,name_a_an,price_a_an,adress_a_an,url_image_a_an
0,Canard de barbarie,12 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5769889_u...
1,Taureau 300 kg,750 000,"Matam, Sénégal",https://images.coinafrique.com/thumb_5737439_u...
2,Oiseaux exotiques,Prix sur demande,"Mbao, Dakar, Sénégal",https://images.coinafrique.com/thumb_5716215_u...
3,Scottish Fold,720 000,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5673757_u...
4,Chaton,750 000,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5673754_u...

In [33]:
# scraper les données sur plusieurs
df4_final = pd.DataFrame()
for ind_page in range(1, 7):
  # url
  url = 'https://sn.coinafrique.com/categorie/autres-animaux?page={ind_page}'
  # récupérer le contenu de la page
  res= get(url)
  # res.content # pour voir le contenu de la page
  # Avoir le contenu dans un objet bs et bien sparsifier
  soup = bs(res.content, 'html.parser')
  # récupérer les informations sur tous les containers
  # récupérer les informations sur tous les containers
  data = []
  for container in containers:
    try:
      # Name aut anim
      name_a_an = container.find('p', 'ad__card-description').a.text
      # price aut anim
      price_a_an = container.find('p', 'ad__card-price').text.strip('CFA')
      # adress aut anim
      adress_a_an = container.find('p', 'ad__card-location').span.text
      # url image aut anim
      url_image_a_an = container.find('img','ad__card-img')['src']
      dic = {
          'name_a_an': name_a_an,
          'price_a_an': price_a_an,
          'adress_a_an': adress_a_an,
          'url_image_a_an':url_image_a_an
      }
      data.append(dic)
    except:
      pass

  # Dataframe
  DF4 = pd.DataFrame(data)
  df4_final = pd.concat([df4_final, DF4], axis = 0).reset_index(drop = True)

In [34]:
# Afficher df_final
df4_final.head()

,name_a_an,price_a_an,adress_a_an,url_image_a_an
0,Canard de barbarie,12 000,"Diamniadio, Sénégal",https://images.coinafrique.com/thumb_5769889_u...
1,Taureau 300 kg,750 000,"Matam, Sénégal",https://images.coinafrique.com/thumb_5737439_u...
2,Oiseaux exotiques,Prix sur demande,"Mbao, Dakar, Sénégal",https://images.coinafrique.com/thumb_5716215_u...
3,Scottish Fold,720 000,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5673757_u...
4,Chaton,750 000,"Point E, Dakar, Sénégal",https://images.coinafrique.com/thumb_5673754_u...

In [35]:
# Dimension
df4_final.shape

(504, 4)